name: Goodreads Zombi Bot

on:
  schedule:
    # Her gün gece 02:00'da tetiklenir (Fakat rastgele uyku ile uyanacak)
    - cron: '0 2 * * *'
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v3

      - name: Rastgele Uyanma (İnsan Taklidi)
        run: |
          # İLK TEST İÇİN BEKLEME SÜRESİ 10 SANİYEYE DÜŞÜRÜLDÜ!
          sleep_time=10
          echo "Bot uyandırıldı fakat dikkat çekmemek için $sleep_time saniye yatakta keyif yapıyor..."
          sleep $sleep_time
          echo "Bot yataktan kalktı ve işe koyuldu!"

      - name: Node.js Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Zombi Botu Çalıştır (1000 Kitaplık Mesai)
        run: npm start

      - name: Çekilen Verileri ve Varsa Hata Loglarını GitHub'a Kaydet
        run: |
          git config --global user.name "ZombiBot"
          git config --global user.email "zombibot@testdeposu.com"
          git add scraped_books.json error.log screenshot.png || echo "Yüklenecek hata dosyası yok"
          git commit -m "Zombi Bot Günlük Mesaisini Tamamladı (1000 Veri Eklendi)" || echo "Değişiklik yok"
          git push
